"""add unique constraints to questions and answers

Revision ID: 1533e9f9efe4
Revises: 95b4ef21e188
Create Date: 2025-12-26 16:58:48.532890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1533e9f9efe4'
down_revision: Union[str, Sequence[str], None] = '95b4ef21e188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_quiz_answer_options_question_id_text_norm', 'quiz_answer_options', ['question_id', sa.literal_column('lower(trim(text))')], unique=True)
    op.create_index('uq_quiz_questions_quiz_id_title_norm', 'quiz_questions', ['quiz_id', sa.literal_column('lower(trim(title))')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_quiz_questions_quiz_id_title_norm', table_name='quiz_questions')
    op.drop_index('uq_quiz_answer_options_question_id_text_norm', table_name='quiz_answer_options')
    # ### end Alembic commands ###
