"""companies table updated (review)

Revision ID: 678a476dddb0
Revises: 2ffca942abc2
Create Date: 2025-11-20 10:33:04.688163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '678a476dddb0'
down_revision: Union[str, Sequence[str], None] = '2ffca942abc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    company_visibility_enum = postgresql.ENUM(
        'hidden',
        'public',
        name='companyvisibilityenum',
        create_type=True
    )
    company_visibility_enum.create(op.get_bind(), checkfirst=True)

    op.execute(
        "ALTER TABLE companies "
        "ALTER COLUMN visibility TYPE companyvisibilityenum "
        "USING visibility::text::companyvisibilityenum"
    )

    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.create_foreign_key(op.f('companies_owner_id_fkey'), 'companies', 'users', ['owner_id'], ['id'])
    op.alter_column('companies', 'visibility',
               existing_type=sa.Enum('HIDDEN', 'PUBLIC', name='companyvisibilityenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    company_visibility_enum = postgresql.ENUM(
        'HIDDEN',
        'PUBLIC',
        name='companyvisibilityenum'
    )
    company_visibility_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
