"""add user additional info

Revision ID: 95b4ef21e188
Revises: 57197babfd2c
Create Date: 2025-12-10 15:49:44.456898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b4ef21e188'
down_revision: Union[str, Sequence[str], None] = '57197babfd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'position')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'about')
    # ### end Alembic commands ###
