"""Invitation status type changed to enum

Revision ID: d84797e31149
Revises: 7c8de2077d53
Create Date: 2025-11-22 07:44:39.638724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84797e31149'
down_revision: Union[str, Sequence[str], None] = '7c8de2077d53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_invitations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELED', name='company_invitation_status', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company_invitations', 'status',
               existing_type=sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'CANCELED', name='company_invitation_status', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
